#!/usr/bin/env python3
"""
data_preprocessing.py

High-performance SAXS simulation and data extraction pipeline for large-scale
protein datasets.

This module converts protein structures into simulated SAXS profiles and
extracts structural parameters required for machine learning models.

Pipeline Overview
-----------------
1. Input:
   Protein structures downloaded from the Protein Data Bank (PDB) located in:
       data/raw_pdb/{pdb_id}.ent

2. Simulation:
   The ATSAS CRYSOL physics engine is used to compute theoretical SAXS
   scattering curves from the atomic coordinates of each protein structure.

3. Feature Extraction:
   From the generated CRYSOL output files:

   - .abs files → SAXS scattering profile
        * q values (momentum transfer)
        * intensity I(q)

   - .log files → structural descriptors
        * Radius of Gyration (Rg)
        * Maximum particle dimension (Dmax)
        * Excluded volume

4. Output:
   Parsed results are returned as dictionaries with the structure:

       {
           "id": pdb_id,
           "q": q_vector,
           "curve": intensity_vector,
           "rg": radius_of_gyration,
           "dmax": maximum_dimension,
           "volume": excluded_volume
       }

5. Parallel Execution:
   The pipeline uses ProcessPoolExecutor to distribute CRYSOL simulations
   across all available CPU cores for efficient processing of large datasets
   (10k–100k proteins).

6. Idempotency / Resume Capability:
   Before running CRYSOL, the pipeline checks whether permanent output files
   already exist in the simulation directory:

       data/simulated_saxs/{pdb_id}.abs
       data/simulated_saxs/{pdb_id}.log

   If both files exist, the simulation step is skipped and the files are
   parsed directly. This allows interrupted pipelines to resume instantly.

7. Fault Tolerance:
   - Each CRYSOL process has a strict timeout of 60 seconds.
   - Failed or hanging simulations are skipped without stopping the pipeline.
   - Temporary files generated by CRYSOL are cleaned automatically.

8. Disk Cleanup:
   After successful extraction, auxiliary CRYSOL files are removed to prevent
   disk bloat:

       *.alm
       *.int
       *.fit
       intermediate *.abs / *.log files

9. Dataset Assembly:
   The processed results are later aggregated by main.py into compressed
   NumPy arrays and stored as:

       data/processed/saxs_dataset.npz

   which contains:
       x       → SAXS intensity curves
       q       → q-vector (momentum transfer)
       y_rg    → radius of gyration
       y_dmax  → maximum dimension
       y_volume→ excluded volume
       ids     → PDB identifiers

Scientific Context
------------------
This pipeline creates a supervised dataset mapping simulated SAXS profiles
to global structural parameters. The dataset is intended for training
machine learning models (e.g., Transformers) that predict structural
properties directly from SAXS curves, enabling fast automated SAXS analysis.

Dependencies
------------
- ATSAS / CRYSOL
- NumPy
- tqdm
- Python concurrent.futures

Typical Dataset Scale
---------------------
Designed to process datasets of:
    10,000 – 100,000 proteins

with full CPU parallelization and robust restart capability.
"""

import glob
import os
import shutil
import subprocess
from concurrent.futures import ProcessPoolExecutor, as_completed

import numpy as np
from tqdm import tqdm


def parse_abs_file(abs_path):
    """Parses the theoretical intensity from CRYSOL .abs files."""
    if not os.path.exists(abs_path):
        return None, None
    try:
        data = np.loadtxt(abs_path, skiprows=1)
        q = data[:, 0]
        intensity = data[:, 1]
        return q, intensity
    except Exception as e:
        tqdm.write(f"Error parsing ABS {abs_path}: {e}")
        return None, None


def parse_log_file(log_path):
    """Extracts Rg, Dmax, and excluded volume labels from CRYSOL .log files."""
    if not os.path.exists(log_path):
        return None, None, None

    rg, dmax, volume = None, None, None

    try:
        with open(log_path, "r") as f:
            for line in f:
                line = line.strip()

                if "Rg (Atoms - Excluded volume + Shell)" in line:
                    rg = float(line.split(":")[-1].strip())

                elif "Envelope Diameter" in line:
                    dmax = float(line.split(":")[-1].strip())

                elif "Excluded Volume [A^3]" in line:
                    volume = float(line.split(":")[-1].strip())

        return rg, dmax, volume

    except Exception:
        return None, None, None


def _safe_remove(path):
    """Delete a file if it exists."""
    try:
        if os.path.exists(path):
            os.remove(path)
    except Exception:
        pass


def _cleanup_crysol_junk(pdb_dir, pdb_id):
    """
    Strictly delete leftover CRYSOL junk from the raw PDB directory.
    Required cleanup:
    - .alm
    - .int
    - .fit
    - original .abs
    - original .log
    Also handles possible 00 suffix files.
    """
    for ext in ["alm", "int", "fit", "abs", "log"]:
        _safe_remove(os.path.join(pdb_dir, f"{pdb_id}.{ext}"))
        _safe_remove(os.path.join(pdb_dir, f"{pdb_id}00.{ext}"))


def process_single_pdb(pdb_path, sim_output_dir):
    """
    Runs CRYSOL and saves the permanent .abs/.log files to sim_output_dir.

    Idempotency:
    - If both permanent .abs and .log already exist in sim_output_dir,
      skip CRYSOL entirely and parse those files directly.

    Timeout handling:
    - CRYSOL is limited to 60 seconds.
    - On timeout, cleanup raw-dir junk and return an error dict.
    """
    pdb_dir = os.path.dirname(pdb_path)
    filename = os.path.basename(pdb_path)
    pdb_id = os.path.splitext(filename)[0]

    os.makedirs(sim_output_dir, exist_ok=True)

    # Permanent output files
    dest_abs = os.path.join(sim_output_dir, f"{pdb_id}.abs")
    dest_log = os.path.join(sim_output_dir, f"{pdb_id}.log")

    # 1. IDEMPOTENCY / RESUME
    if os.path.exists(dest_abs) and os.path.exists(dest_log):
        q, curve = parse_abs_file(dest_abs)
        rg, dmax, volume = parse_log_file(dest_log)
        return {
            "id": pdb_id,
            "q": q,
            "curve": curve,
            "rg": rg,
            "dmax": dmax,
            "volume": volume,
        }

    cmd = ["crysol", filename]

    try:
        # 2. TIMEOUTS AND ERROR HANDLING
        subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            cwd=pdb_dir,
            timeout=60,
            text=True,
        )

        # Internal paths where CRYSOL may dump output
        src_abs = os.path.join(pdb_dir, f"{pdb_id}00.abs")
        src_log = os.path.join(pdb_dir, f"{pdb_id}00.log")

        # Fallback naming
        if not os.path.exists(src_abs):
            src_abs = os.path.join(pdb_dir, f"{pdb_id}.abs")
            src_log = os.path.join(pdb_dir, f"{pdb_id}.log")

        # Copy permanent outputs
        if os.path.exists(src_abs):
            shutil.copy2(src_abs, dest_abs)
        if os.path.exists(src_log):
            shutil.copy2(src_log, dest_log)

        # Parse permanent files
        q, curve = parse_abs_file(dest_abs)
        rg, dmax = parse_log_file(dest_log)

        # Strictly delete only the leftover raw-dir junk.
        _cleanup_crysol_junk(pdb_dir, pdb_id)

        return {
            "id": pdb_id,
            "q": q,
            "curve": curve,
            "rg": rg,
            "dmax": dmax,
            "volume": volume,
        }

    except subprocess.TimeoutExpired:
        tqdm.write(f"WARNING: {pdb_id} timed out after 60 seconds.")
        _cleanup_crysol_junk(pdb_dir, pdb_id)
        return {"id": pdb_id, "error": "Timeout"}

    except Exception as e:
        _cleanup_crysol_junk(pdb_dir, pdb_id)
        return {"id": pdb_id, "error": str(e)}


def run_simulation_pipeline(input_dir, sim_output_dir):
    """
    Orchestrates parallel execution.

    Requirements implemented:
    - Uses all CPU cores
    - Uses as_completed instead of executor.map
    - Wraps completion loop in tqdm for progress tracking
    """
    os.makedirs(sim_output_dir, exist_ok=True)

    search_pattern = os.path.join(input_dir, "**", "*.ent")
    pdbs = glob.glob(search_pattern, recursive=True)
    pdbs += glob.glob(os.path.join(input_dir, "**", "*.pdb"), recursive=True)

    if not pdbs:
        tqdm.write(f"No files found in {input_dir}")
        return []

    tqdm.write(f"Found {len(pdbs)} files. Generating simulated curves...")

    results = []
    max_workers = os.cpu_count() or 1

    with ProcessPoolExecutor(max_workers=max_workers) as executor:
        future_to_pdb = {
            executor.submit(process_single_pdb, pdb_path, sim_output_dir): pdb_path
            for pdb_path in pdbs
        }

        for future in tqdm(
            as_completed(future_to_pdb),
            total=len(future_to_pdb),
            desc="Processing proteins",
        ):
            pdb_path = future_to_pdb[future]
            pdb_id = os.path.splitext(os.path.basename(pdb_path))[0]

            try:
                result = future.result()
                results.append(result)
            except Exception as e:
                tqdm.write(f"Failed processing {pdb_id}: {e}")
                results.append({"id": pdb_id, "error": str(e)})

    valid_data = [
        r
        for r in results
        if "curve" in r
        and r["curve"] is not None
        and r.get("rg") is not None
        and r.get("dmax") is not None
        and r.get("volume") is not None
    ]
    return valid_data
